signaturesymbols = {
'ECDSA'             : 'Delphi Elliptic Curve DSA (ECDSA)',
'ECElGamal'         : 'Delphi Elliptic Curve ElGamal (ECElGamal)',
'ECGFp'             : 'Delphi Elliptic Curve over GF (ECGFp)',
'FGInt'             : 'Delphi BigNum Library (FGInt)',
'FGIntDSA'          : 'Delphi DSA (FGIntDSA)',
'FGIntElGamal'      : 'Delphi Elgamal (FGIntElGamal)',
'FGIntGOSTDSA'      : 'Delphi GOSTDSA (FGIntGOSTDSA)',
'FGIntRSA'          : 'Delphi RSA (FGIntRSA)',
'CryptDecrypt'      : 'MS Crypto API Cipher (CryptDecrypt RC2,RC4)',
'CryptEncrypt'      : 'MS Crypto API Cipher (CryptEncrypt RC2,RC4)',
'CryptCreateHash'   : 'MS Crypto API Hash (CryptCreateHash MD2,MD5,SHA)',
'CryptDestroyHash'  : 'MS Crypto API Hash (CryptDestroyHash MD2,MD5,SHA)',
'CryptGetHashParam' : 'MS Crypto API Hash (CryptGetHashParam MD2,MD5,SHA)',
'CryptHashData'     : 'MS Crypto API Hash (CryptHashData MD2,MD5,SHA)',
'aes' : 'Some symbol with aes in it',
'rc4' : 'Some symbol with rc4 in it',
'des' : 'Some symbol with des in it',
'md5' : 'Some symbol with md5 in it',
'rsa' : 'Some symbol with rsa in it',
'xor' : 'Some symbol with xor in it',
}